name: Laravel 3-Tier GitHub Action with CI/CD

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  mycid:
    name: My Laravel CICD App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Apache2
        run: sudo apt-get update && sudo apt-get install -y apache2

      - name: Setup PHP with PECL extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick, swoole, intl, zip, mbstring, gd, zlib

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Create SSH Directory
        run: mkdir -p ~/.ssh

      - name: Decode SSH Key
        id: decode_key
        run: |
          echo "${{ secrets.SSH_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -l ~/.ssh
          cat ~/.ssh/id_rsa

      - name: Add SSH Key to SSH Agent
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-add -l

      - name: Add Host Key to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts

      - name: Verify SSH Connection
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} echo "SSH connection successful"

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ~/.ssh/id_rsa
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/var/www/html/laravelcicd"

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ~/.ssh/id_rsa
          port: ${{ secrets.SSH_PORT }}
          script: ./scripts/deploy.sh
